### ISSUE TITLE
composer require marmelab/microrest "~1.0@dev"

### ISSUE THREAD

**Issue by ajacquelin** [marmelab/microrest.php#11]
Hello,
I'm trying to install microrest with composer and I get an error.
command:
composer require marmelab/microrest "~1.0@dev"

the error:
  Problem 1
    - Installation request for marmelab/microrest ~1.0@dev -> satisfiable by marmelab/microrest[1.0.x-dev].
    - marmelab/microrest 1.0.x-dev requires alecsammon/php-raml-parser 1.0.0.x-dev -> no matching package found.

Do you know how can I fix it ? I'm not familiar with composer so any help will be very much appreciated.

Cheers,

**Comment by romgapuz** [comment]
This was fixed by https://github.com/tmeliberty/microrest.php/commit/575ed22147783218796fdbb1431a3b227c60b049 but was not merged. So you need to override the dependency to this repo.

The solution is https://getcomposer.org/doc/articles/aliases.md#require-inline-alias. Use the composer.json below:

{
    "require": {
        "marmelab/microrest": "~1.0@dev",
        "alecsammon/php-raml-parser": "dev-master as 1.0.0.x-dev"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/tmeliberty/microrest.php.git"
        }
    ]
}

**Comment by jeromemacias** [comment]
@tmeliberty Can you open a pull request please ?

**Comment by jeromemacias** [comment]
Fixed by 7034582
